project:
  name: quickstart-ibm-maximo
  owner: quickstart-eng@amazon.com
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_regional_buckets: true
  shorten_stack_name: false
  regions:
  - us-east-1
  - us-east-2
  - us-west-2
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - ap-northeast-1
  - ap-southeast-1
  - ap-southeast-2
  s3_bucket: ''
tests:
  maximo-1:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      DBPassword: $[taskcat_genpass_8A]
      DockerRegistryEntitlementKey: override
      DomainAdminPassword: $[taskcat_genpass_12A]
      KeyPairName: $[taskcat_getkeypair]
      MaximoFilesLocation: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 10.0.0.0/16
      RemoteAccessCIDR: 10.0.0.0/16
      SSLCertARN: override
      VPCCIDR: 10.0.0.0/16
    regions:
    - us-east-1
    - us-east-2
    - us-west-2
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    s3_bucket: ''
    template: templates/maximo-master.template.yaml
