// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.
. Use the Region selector in the navigation bar to choose the AWS Region where you want to deploy FileNet Content Manager on AWS. The deployment is restricted to AWS Regions with at least two Availability Zones.
. Select the key pair that you created earlier. In the navigation pane of the Amazon EC2 console, choose Key Pairs, and then choose your key pair from the list.
. Choose an existing S3 bucket or create a new one to store the prerequisite database client and deployment log files.
. Use the AWS Certificate Manager to create a Secure Sockets Layer (SSL) certificate.

=== Download IBM Maximo binaries and Oracle SQL client and JDBC driver
. Download IBM Maximo Asset Management V7.6.1 binaries from https://www.ibm.com/software/passportadvantage/index.html[Passport Advantage] and then upload them to the S3 bucket you selected or created earlier.  The following IBM Maximo files are required:
 . IBM Enterprise Deployment (formerly known as IBM Installation Manager) binaries: IED_V1.8.8_Wins_Linux_86.zip
 . IBM Maximo Asset Management V7.6.1 binaries: MAM_7.6.1.0_LINUX64.tar.gz
 . IBM WebSphere Application Server traditional V9 binaries: WAS_ND_V9.0_MP_ML.zip
 . IBM Java SDK V8 binaries:
  . was.repo.9000.java8_part1.zip
  . was.repo.9000.java8_part2.zip
  . was.repo.9000.java8_part3.zip
 . IBM Maximo Utilities module binaries: MAXIMO_UTILITIES_7.6_MP_ML.zip
 . Oracle sqlplus instant client:
  . instantclient-sqlplus-linux.x64-19.6.0.0.0dbru.zip
  . instantclient-basiclite-linux.x64-19.6.0.0.0dbru.zip

=== Launch the Quick Start
. Sign in to your AWS account, and launch the AWS CloudFormation template.  The entire deployment process takes about 2 hours to complete
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar and change it if necessary. This is where the network infrastructure for IBM Maximo is built. The template is launched in the US East (Virginia) Region by default.
. On the *Select Template* page, keep the default setting for the template URL, and then choose *Next*
. On the *Specify Details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary.
. On the *Options* page, you can specify tags (key value pairs) for resources in your stack and set advanced options. When you’re done, choose *Next*.
. On the *Review* page, review and confirm the template settings. Under *Capabilities*, select the two check boxes to acknowledge that the template creates IAM resources and that it might require the capability to auto-expand macros.
. Choose *Create* to deploy the stack.
. Monitor the status of the stack. When the status is CREATE_COMPLETE, the IBM Maximo cluster is ready.
. Check the stack’s *Outputs* tab to view the created resources.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[deployment options] earlier in this guide.

[cols=2*]
|===
^|http://qs_launch_link[Deploy {partner-product-short-name} into a new VPC on AWS^]
^|http://qs_template_link[View template^]

^|http://qs_launch_link[Deploy {partner-product-short-name} into an existing VPC on AWS^]
^|http://qs_template_link[View template^]
|===

WARNING: If you’re deploying {partner-product-short-name} into an existing VPC, make sure that your VPC has two private subnets in different Availability Zones for the workload instances, and that the subnets aren’t shared. This Quick Start doesn’t support https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[shared subnets^]. These subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] in their route tables, to allow the instances to download packages and software without exposing them to the internet.

Also, make sure that the domain name option in the DHCP options is configured as explained in the http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[Amazon VPC documentation^]. You provide your VPC settings when you launch the Quick Start.

Each deployment takes about {deployment_time} to complete.

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-short-name} will be built. The template is launched in the {default_deployment_region} Region by default.

// *Note:* This deployment includes Amazon EFS, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/elasticfilesystem.html[endpoints and quotas webpage].

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary.

// In the following tables, parameters are listed by category and described separately for the two deployment options:

// * Parameters for deploying {partner-product-short-name} into a new VPC
// * Parameters for deploying {partner-product-short-name} into an existing VPC