// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding. 
// Include the benefits of using the software on AWS, and provide details on usage scenarios.

== IBM Maximo on AWS

IBM Maximo enterprise asset management (EAM) is crucial to obtaining the insights and visibility needed to maintain and control intelligent assets and equipment. 
Reimagine your operations with EAM solutions designed to optimize the quality and utilization of your assets throughout their lifecycle, increase 
productive uptime through preventative and predictive maintenance, drive efficiency and reduce operating costs.

IBM Maximo® Application Suite helps drive operational resiliency and reliability with condition-based asset maintenance. With expanded access to CMMS, EAM and 
asset performance management applications, your teams can reach across the enterprise to unify operations and maintain business continuity, even under rapidly 
changing or disruptive conditions.

== Key capabilities of Maximo Application Suite:

- Integrated suite of applications
- Simplified licensing including single contract and pricing metric
- Comprehensive view of your assets

== APM for Energy and Utilities

Get a detailed, accurate understanding of historical and current asset and network performance through data integration, analytics and visualization, to enhance 
performance management, situational awareness, investment planning, and connectivity model verification.

IBM Maximo uses a range of AWS services and features, including:
- Security groups
- Amazon EC2
- Amazon EBS storage
- Amazon RDS
- AWS CloudFormation
- Elastic Load Balancing
After deployment, you can configure and extend IBM Maximo for your specific
business applications and use cases. For more information about IBM Maximo
Manager, see https://www.ibm.com/products/maximo.