AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This main template creates a VPC infrastructure for a multi-AZ, multi-tier deployment
  of a WAS on AWS. It deploys a VPC with bastions and a WAS cluster behind
  an ELB. The cluster is configured to use an S3 bucket for storage  **WARNING** This
  template creates EC2 instances and related resources. You will be billed for the
  AWS resources used if you create a stack from this template. (qs-1r4dcoie9)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Parameters for launching into a new VPC"
    Order: "1"
    OptionalParameters:
      - ALBSSLCertificateARN
      - SiteDomain
      - Route53HostedZoneId
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - AvailabilityZones
          - VPCCIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - RemoteAccessCIDR
      - Label:
          default: Bastion host configuration
        Parameters:
          - KeyPairName
          - BastionAMIOS
          - BastionInstanceType
      - Label:
          default: WAS nodes configuration
        Parameters:
          - WASInstanceType
          - WASNodesMinSize
          - WASNodesMaxSize
          - WASNodesDesiredCapacity
          - WebAccessCIDR
          - DeployUtilities
      - Label:
          default: SSL configuration
        Parameters:
          - ALBSSLCertificateARN
          - SiteDomain
          - Route53HostedZoneId
      - Label:
          default: IBM Maximo configuration
        Parameters:
          - MaximoFilesLocation
      - Label:
          default: Oracle RDS configuration
        Parameters:
          - ORAVersion
          - DBInstanceIdentifier
          - DBInstanceClass
          - DBName
          - DBUser
          - DBPassword
          - DBMultiZone
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      ALBSSLCertificateARN:
        default: ALB SSL certificate ARN
      SiteDomain:
        default: Maximo site domain
      Route53HostedZoneId:
        default: Route 53 hosted zone ID
      AvailabilityZones:
        default: Availability Zones
      BastionAMIOS:
        default: Bastion AMI operating system
      BastionInstanceType:
        default: Bastion instance type
      KeyPairName:
        default: Key pair name
      # WAS Parameters
      WASInstanceType:
        default: WAS server instance type
      WASNodesDesiredCapacity:
        default: WAS nodes desired capacity
      WASNodesMaxSize:
        default: WAS odes max size
      WASNodesMinSize:
        default: WAS nodes min size
      WebAccessCIDR:
        default: Maximo web access CIDR
      DeployUtilities:
        default: Deploy utilities modules
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      # Oracle RDS Parameters
      ORAVersion:
        default: Oracle database version
      DBInstanceIdentifier:
        default: Oracle database instance name
      DBInstanceClass:
        default: Oracle database instance type
      DBName:
        default: Oracle database name
      DBUser:
        default: Oracle database admin user name
      DBPassword:
        default: Oracle database admin password
      DBMultiZone:
        default: High availability (Multi-AZ) for Oracle RDS
      # S3 Bucket  Parameters
      MaximoFilesLocation:
        default: Maximo files location
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      RemoteAccessCIDR:
        default: Bastion external access CIDR
      VPCCIDR:
        default: VPC CIDR
Parameters:
  ALBSSLCertificateARN:
    Default: ''
    Description: '[Optional] ARN of the SSL certificate to be used for the Application Load Balancer'
    Type: String
  SiteDomain:
    Description:  "[Optional] Domain name of the maximo site. e.g. maximo.example.com. Valid FQDN required when using SSL."
    AllowedPattern: (?!-)[a-zA-Z0-9-.]*(?<!-)
    ConstraintDescription: Must be a valid fully-qualified domain name.
    Type: String
    Default: ""
  Route53HostedZoneId:
    Description:  "[Optional] Route53 hosted zone ID where DNS record for Maximo will be added."
    Type: String
    Default: ""
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. Only
      two Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  BastionAMIOS:
    AllowedValues:
      - Amazon-Linux2-HVM
      - Amazon-Linux-HVM
      - CentOS-7-HVM
      - Ubuntu-Server-14.04-LTS-HVM
      - Ubuntu-Server-16.04-LTS-HVM
    Default: Amazon-Linux2-HVM
    Description: The Linux distribution for the AMI to be used for the bastion instances
    Type: String
  BastionInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for the bastion instances
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  WASInstanceType:
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - r3.large
      - r3.xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
    ConstraintDescription: Must contain valid instance type
    Default: m5.xlarge
    Description: EC2 instance type for the WAS instances
    Type: String
  WASNodesDesiredCapacity:
    Default: '2'
    Description: The desired capacity for the WAS nodes Auto Scaling group
    Type: String
  WASNodesMaxSize:
    Default: '4'
    Description: The maximum size of the Auto Scaling group
    Type: String
  WASNodesMinSize:
    Default: '2'
    Description: The minimum size of the Auto Scaling group
    Type: String
  WebAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the Maximo URL. We recommend
      that you set this value to a trusted IP range.
    Type: String
  DeployUtilities:
    AllowedValues:
      - 'Yes'
      - 'No'
    ConstraintDescription: Choose Yes to deploy utilities modules
    Default: 'No'
    Description: Choose Yes to deploy utilities modules.
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1 located in Availability Zone 1
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the public (DMZ) subnet 1 located in Availability
      Zone 1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the public (DMZ) subnet 2 located in Availability
      Zone 2
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-ibm-maximo/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the bastions. We recommend
      that you set this value to a trusted IP range.
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
  MaximoFilesLocation:
    Description: Provide the S3 location of the downloaded Maximo, WAS, and Oracle client files (do not include the s3:// and the trailing forward slash).
      E.g., if the location is "s3://ibm-maximo-assets/instllation_files", then enter "ibm-maximo-assets/instllation_files".
      Refer to the deployment guide for more information on downloading the client files and obtaining the location.
    Type: String
  # Oracle RDS Database Parameters
  ORAVersion:
    AllowedValues:
      - Enterprise-Edition-12.2-BYOL
      - Enterprise-Edition-18.0-BYOL
      - Standard-Edition-Two-12.2-License-Included
      - Standard-Edition-Two-18.0-License-Included
    Default: Standard-Edition-Two-18.0-License-Included
    Description: Amazon RDS Oracle version.
    Type: String
  DBInstanceClass:
    AllowedValues:
      - db.m4.xlarge
      - db.m4.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
    Default: db.m5.large
    Description: Amazon RDS instance type for the Oracle database instance.
    Type: String
  DBInstanceIdentifier:
    Default: ORCL
    Description: The database instance name.
    Type: String
    MinLength: '1'
    MaxLength: '8'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBName:
    Default: maximo
    Description: The database name.
    Type: String
    MinLength: '1'
    MaxLength: '8'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    Default: Admin
    Description: The database admin account user name.
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password. Must be at least 8 characters containing letters, numbers only.
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBMultiZone:
    Description: Choose false to disable high availability (Multi-AZ) configuration for Oracle RDS.
      More information is available here - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref 'AvailabilityZones'
        KeyPairName: !Ref 'KeyPairName'
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref 'PrivateSubnet1CIDR'
        PrivateSubnet2ACIDR: !Ref 'PrivateSubnet2CIDR'
        PublicSubnet1CIDR: !Ref 'PublicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'PublicSubnet2CIDR'
        VPCCIDR: !Ref 'VPCCIDR'
  MaximoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/maximo.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
        PrivateSubnet1ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
        PrivateSubnet2ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
        PublicSubnet1ID: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        PublicSubnet2ID: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
        KeyPairName: !Ref 'KeyPairName'
        BastionAMIOS: !Ref 'BastionAMIOS'
        BastionInstanceType: !Ref 'BastionInstanceType'
        WASInstanceType: !Ref 'WASInstanceType'
        WASNodesDesiredCapacity: !Ref 'WASNodesDesiredCapacity'
        WASNodesMaxSize: !Ref 'WASNodesMaxSize'
        WASNodesMinSize: !Ref 'WASNodesMinSize'
        DeployUtilities:  !Ref 'DeployUtilities'
        ALBSSLCertificateARN: !Ref 'ALBSSLCertificateARN'
        MaximoFilesLocation: !Ref 'MaximoFilesLocation'
        DBInstanceClass: !Ref 'DBInstanceClass'
        DBInstanceIdentifier: !Ref 'DBInstanceIdentifier'
        DBName: !Ref 'DBName'
        ORAVersion: !Ref 'ORAVersion'
        DBUser: !Ref 'DBUser'
        DBPassword: !Ref 'DBPassword'
        DBMultiZone: !Ref 'DBMultiZone'
        QSS3BucketName: !Ref 'QSS3BucketName'
        QSS3BucketRegion: !Ref 'QSS3BucketRegion'
        QSS3KeyPrefix: !Ref 'QSS3KeyPrefix'
        RemoteAccessCIDR: !Ref 'RemoteAccessCIDR'
        WebAccessCIDR: !Ref 'WebAccessCIDR'
        SiteDomain: !Ref 'SiteDomain'
        Route53HostedZoneId:  !Ref 'Route53HostedZoneId'


Outputs:
  WebsiteURL:
    Description: URL for newly created WAS stack
    Value: !GetAtt 'MaximoStack.Outputs.WebsiteURL'
  PrimaryJDBCConnectionString:
    Description: JDBC connection string for the primary database
    Value: !GetAtt 'MaximoStack.Outputs.PrimaryJDBCConnectionString'
